import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import UserProvider from "@/components/providers/UserProvider";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog",
  description: "Blog generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <UserProvider>
        <body className={inter.className}>{
          <div className="relative flex flex-col items-center bg-light-1">
            <Navbar />
            {children}
          </div>
        }</body>
      </UserProvider>
    </html>
  );
}
